.github/workflows/builddocs_win19.job, .github/workflows/createjars_core5.0_win19.job, .github/workflows/docs.yaml, .github/workflows/linux.yml, .github/workflows/release.yaml, .github/workflows/windows.yaml, JCOReflector/engine/JavaBuilder.cs, netreflected-tests/java/src/nettest/HelloNETSocketClient.java, netreflected-tests/java/src/nettest/HelloNETSocketServer.java, netreflected/docs/README.md
Added workflows to update documentation when the code is updated
N/A
The change allows to generate documentation without manual intervention (#7)
N/A
=> Added documentation generation

.github/workflows/maven.yaml, JCOReflector/engine/JCOPOMJCOReflector.template, netreflected-tests/maven/.idea/.gitignore, netreflected-tests/maven/.idea/.name, netreflected-tests/maven/.idea/codeStyles/Project.xml, netreflected-tests/maven/.idea/codeStyles/codeStyleConfig.xml, netreflected-tests/maven/.idea/compiler.xml, netreflected-tests/maven/.idea/jarRepositories.xml, netreflected-tests/maven/.idea/misc.xml, netreflected-tests/maven/.idea/vcs.xml, netreflected-tests/maven/netreflected-tests.iml, netreflected-tests/maven/pom.xml
The publication on Maven Central was updated to avoid dependency on missing JCOBridge artifact in Maven Central
Closed #28 
Solves https://github.com/masesgroup/JCOReflector/issues/28#issuecomment-818368818 and https://github.com/masesgroup/JCOReflector/issues/28#issuecomment-818373987
With publication on Maven Central in the fork
=> Update Maven Central publication

.github/workflows/pullrequests.yaml, .github/workflows/testbranch.yaml
Split workflow to have one dedicated to PR
#21
Actual workflow fails when used for PR
Not tested
=> #21: changed workflows to follow request on https://github.com/masesgroup/JCOReflector/issues/21#issuecomment-865369330

.github/workflows/linux.yaml, .github/workflows/pullrequests.yaml, .github/workflows/reflect_net461.job, .github/workflows/reflect_net5.0.job, .github/workflows/reflect_netcoreapp3.1.job, .github/workflows/testbranch.yaml, .github/workflows/windows.yaml, JCOReflector/CLI/JCOReflectorCLI.csproj, JCOReflector/GUI/JCOReflectorGUI.csproj, JCOReflector/GUI/MainWindow.xaml, JCOReflector/GUI/MainWindow.xaml.cs, JCOReflector/engine/Const.cs, JCOReflector/engine/JCOReflectorEngine.csproj, JCOReflector/engine/Reflector.cs, JCOReflector/engine/SharedClasses.cs, netreflected-tests/java/src/hierarchy/HelloHierarchy.java, netreflected-tests/java/src/hierarchy/HelloInterfaces.java, netreflected-tests/java/src/mscorlib/HelloIterator.java, netreflected-tests/java/src/nettest/HelloNETSocket.java, netreflected-tests/java/src/refout/HelloRefOut.java, netreflected-tests/kotlin/src/main/kotlin/refout/HelloRefOut.kt, netreflected-tests/scala/src/main/scala/refout/HelloRefOut.scala, netreflected/src/JCOReflector/org/mases/jcobridge/netreflection/JCORefOut.java, netreflected/src/JCOReflector/org/mases/jcobridge/netreflection/NetObjectEnumerable.java
Added management of ref and out keywords within methods
Closing #9
Closing #20 
This PR adds management of ref-out and try to close issue #9.
Executed the tests available in the repo
=> Added ref-out management

.github/workflows/linux.yaml, .github/workflows/pullrequests.yaml, .github/workflows/testbranch.yaml, .github/workflows/windows.yaml, netreflected-tests/java/src/refout/HelloRefOutBase.java, netreflected-tests/kotlin/src/main/kotlin/refout/HelloRefOutBase.kt, netreflected-tests/scala/src/main/scala/nettest/HelloNETSocket.scala, netreflected-tests/scala/src/main/scala/nettest/HelloNETSocketClient.scala, netreflected-tests/scala/src/main/scala/nettest/HelloNETSocketServer.scala, netreflected-tests/scala/src/main/scala/refout/HelloRefOutBase.scala, netreflected/src/JCOReflector/system/Boolean.java, netreflected/src/JCOReflector/system/Byte.java, netreflected/src/JCOReflector/system/Double.java, netreflected/src/JCOReflector/system/Float.java, netreflected/src/JCOReflector/system/Int16.java, netreflected/src/JCOReflector/system/Int32.java, netreflected/src/JCOReflector/system/Int64.java
Basic types under JCOReflector are aligned to cover use of JCORefOut
Closed #9 
The basic types where not changed in #42 and a specific test was added for them
Test available in the repo
=> Refinement on #42

.github/workflows/docs.yaml
net6.0 docs misaligned
#61 
Previous docs.yaml execution misaligned submodule references
N/A
=> #61: fixed error during execution of docs.yaml

_data/navigation.yml
Site update
#61
Missing reference to .NET 6 docs
N/A
=> #61 (https://github.com/masesgroup/JCOReflector/issues/61#issuecomment-968988532): added .NET 6 link

.github/workflows/release.yaml
Refix https://github.com/masesgroup/JCOReflector/issues/61#issuecomment-969178367
#61 
https://github.com/masesgroup/JCOReflector/issues/61#issuecomment-969178367
N/A
=> #61 (https://github.com/masesgroup/JCOReflector/issues/61#issuecomment-969178367): refix issue

.github/workflows/maven.yaml, .github/workflows/release.yaml, src/CLI/JCOReflectorCLI.csproj, src/GUI/JCOReflectorGUI.csproj, src/engine/JCOPOMExtension.template, src/engine/JCOPOMJCOReflector.template, src/engine/JCOReflectorEngine.csproj
Upgrade to latest JCOBridge version
#61 
A new version of JCOBridge was released
Not tested
=> #61: upgrade to JCOBridge 2.4.1

.github/workflows/maven.yaml, .github/workflows/release.yaml, src/CLI/JCOReflectorCLI.csproj, src/GUI/JCOReflectorGUI.csproj, src/engine/JCOPOMExtension.template, src/engine/JCOPOMJCOReflector.template, src/engine/JCOReflectorEngine.csproj
Upgrade to latest JCOBridge Engine version
#61 
A new version of the engine was released
Not tested
=> #61: update to JCOBridge 2.4.3

src/CLI/JCOReflectorCLI.csproj, src/CLI/JCOReflectorCLI.nuspec, src/GUI/JCOReflectorGUI.csproj, src/engine/JCOReflectorEngine.csproj, src/engine/Reflector.cs
Fix previous commit error
Fixing #77 
The previous PR does not solved the issue
Specific smoke test
=> Keyword in namespace

.github/workflows/GetLicense.ps1, .github/workflows/SaveLicense.ps1, .github/workflows/linux.yaml, .github/workflows/maven.yaml, .github/workflows/pullrequests.yaml, .github/workflows/release.yaml, .github/workflows/testbranch.yaml, .github/workflows/windows.yaml, src/CLI/JCOReflectorCLI.csproj, src/CLI/JCOReflectorCLI.nuspec, src/GUI/AssemblyCollectionControl.xaml, src/GUI/AssemblyCollectionControl.xaml.cs, src/GUI/JCOReflectorGUI.csproj, src/GUI/MainWindow.xaml, src/GUI/MainWindow.xaml.cs, src/engine/JCOPOMExtension.template, src/engine/JCOPOMJCOReflector.template, src/engine/JCOReflectorEngine.csproj, src/engine/Reflector.cs, src/engine/SharedClasses.cs
Added new option to reflect namespace ending with Internal; plus JCOBridge upgraded to version 2.4.7
closed #61 
closed #83 
closed #84
=> Added namespace ending with Internal option and upgrade to JCOBridge 247

README.md, netreflected/README.md, src/CLI/JCOReflectorCLI.csproj, src/CLI/JCOReflectorCLI.nuspec, src/GUI/JCOReflectorGUI.csproj, src/engine/Const.cs, src/engine/JCOReflectorEngine.csproj, src/engine/JavaBuilder.cs, src/engine/Reflector.cs, src/engine/SharedClasses.cs
Update to fix exception report
closed #91 
closed #93 
Tested locally and in github actions
=> #91: update engine with ReportException

.github/workflows/windows.yaml, src/engine/SharedClasses.cs
Update to fix issue
closed #93
Tested locally and in github actions
=> Solved #93

src/engine/JCOReflectorEngine.csproj, src/engine/SharedClasses.cs
New behavior of assembly reflection check
closed #99
=> #99: assembly list embedded into the engine

src/engine/Reflector.cs
Update engine to manage Type without a namespace
closed #102
=> #102: return an empty string if Namespace of Type is null

src/CLI/JCOReflectorCLI.csproj, src/CLI/JCOReflectorCLI.nuspec, src/GUI/JCOReflectorGUI.csproj, src/engine/JCOReflectorEngine.csproj, src/engine/Reflector.cs
=> Version upgrade

src/CLI/JCOReflectorCLI.csproj, src/CLI/JCOReflectorCLI.nuspec, src/CLI/Program.cs, src/CLI/app.manifest, src/GUI/JCOReflectorGUI.csproj, src/GUI/app.manifest, src/engine/JCOReflectorEngine.csproj
Now JCOReflector supports long path in windows
Follows the same behavior introduced with masesgroup/NuReflector#22
=> Long path aware

.github/workflows/docs.yaml, .github/workflows/linux.yaml, .github/workflows/maven.yaml, .github/workflows/pullrequests.yaml, .github/workflows/release.yaml, .github/workflows/testbranch.yaml, .github/workflows/windows.yaml, README.md, _data/navigation.yml, netreflected-tests/java/.classpath, netreflected-tests/java/.idea/codeStyles/Project.xml, netreflected-tests/java/netreflected-tests.iml, src/CLI/JCOReflectorCLI.csproj, src/CLI/JCOReflectorCLI.nuspec, src/GUI/JCOReflectorGUI.csproj, src/engine/JCOManifest.template, src/engine/JCOPOMExtension.template, src/engine/JCOPOMJCOReflector.template, src/engine/JCOReflectorEngine.csproj
This PR removes .NET 5 and upgrades dependencies to the latest version
closed #111
=> Removed .NET 5 

.github/workflows/pullrequests.yaml, .github/workflows/testbranch.yaml, .github/workflows/windows.yaml
Updates to remove last warning for deprecated API
Fix #116
=> #116: fix warning of jitterbit/get-changed-files@v1

.github/workflows/linux.yaml, .github/workflows/maven.yaml, .github/workflows/release.yaml, .github/workflows/testbranch.yaml, .github/workflows/windows.yaml, src/engine/JCOReflectorEngine.csproj
Update JCOBridge and bug fix on workflows
Closed #118
=> #118: Update to JCOBridge 2.5.2 and fix linux.yaml

src/engine/JCOPOMExtension.template, src/engine/JCOPOMJCOReflector.template
Fix JCOBridge version in POM
Closed #118
=> #118: update POM to align to JCOBridge version

_data/navigation.yml
Fix references in website
Fix #118
=> Fix website

.github/workflows/linux.yaml, .github/workflows/maven.yaml, .github/workflows/release.yaml, .github/workflows/testbranch.yaml, .github/workflows/windows.yaml, src/CLI/JCOReflectorCLI.csproj, src/CLI/JCOReflectorCLI.nuspec, src/GUI/JCOReflectorGUI.csproj, src/engine/Const.cs, src/engine/JCOPOMExtension.template, src/engine/JCOPOMJCOReflector.template, src/engine/JCOReflectorEngine.csproj, src/engine/JavaBuilder.cs
This PR updates to JCOBridge 2.5.3 and insert automatically JCOBrdge version inside the POM
Closed #126
=> #126: update to JCOBridge 2.5.3

.github/workflows/maven.yaml, src/engine/JCObjectReflectorClass.template, src/engine/JCObjectReflectorEnum.template, src/engine/JCObjectReflectorEnumerator.template, src/engine/JCObjectReflectorInterface.template, src/engine/JCObjectReflectorInterfaceClass.template, src/engine/JCObjectReflectorNativeDelegateClass.template, src/engine/JCObjectReflectorNonVoidDelegateInterface.template, src/engine/JCObjectReflectorObjectDelegateClass.template, src/engine/JCObjectReflectorThrowableClass.template, src/engine/JCObjectReflectorVoidDelegateClass.template, src/engine/JCObjectReflectorVoidDelegateInterface.template
Changed templates to generated more info in documentation
Closed #128
=> Add more info within generated documentation and site

.github/workflows/maven.yaml, .github/workflows/release.yaml
Update release.yaml with rules applied on maven.yaml
Will be tested on first release
=> #130: fixed release.yaml with same rules of maven.yaml

.github/workflows/release.yaml
=> #130: fix wrong filename for .NET 7

.github/workflows/release.yaml
=> #130: extra fix on path
